apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service-deployment
  labels:
    app: redis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
      - name: redis-service
        image: systeamorg/redis-service
        imagePullPolicy: Never
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-service
spec:
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30001
    protocol: TCP
    name: tcp
  type: NodePort
  selector:
    app: redis-service
